Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Models;
using Demo.PL.Helpers;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    //[AllowAnonymous]
    [Authorize]
    public class EmployeeController : Controller
    {
        //private readonly IEmployeeRepository _employeeRepository;
        //private readonly IDepartmentRepository _departmentRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(
            IUnitOfWork unitOfWork,
            IMapper mapper)
        {
            //_employeeRepository = employeeRepository;
            //_departmentRepository = departmentRepository;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        // /Employee/Index
        public async Task<IActionResult> Index(string SearchValue)
        {
            IEnumerable<Employee> Emps;

            if (string.IsNullOrEmpty(SearchValue))
                Emps = await _unitOfWork.EmployeeRepository.GetAll();

            else
                Emps = _unitOfWork.EmployeeRepository.SearchEmployeeByName(SearchValue);

            var mappedEmps = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(Emps);
            return View(mappedEmps);

        }
        // /Employee/Create
        //[HttpGet]
        public IActionResult Create()
        {
            //ViewBag.Departments = _departmentRepository.GetAll();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (ModelState.IsValid) // Server Side Validation
            {
                // Manual Mapping
                ///var mappedEmp = new Employee()
                ///{
                ///    Name = employeeVM.Name,
                ///    Address = employeeVM.Address,
                ///    Age = employeeVM.Age,
                ///    DepartmentId = employeeVM.DepartmentId,
                ///    Email = employeeVM.Email,
                ///    IsActive = employeeVM.IsActive,
                ///    PhoneNumber = employeeVM.PhoneNumber,
                ///    HireDate = employeeVM.HireDate,
                ///    Salary = employeeVM.Salary
                ///};

                employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                await _unitOfWork.EmployeeRepository.Add(mappedEmp);
                // Update
                // Delete

                await _unitOfWork.Complete();


                return RedirectToAction(nameof(Index));
            }
            return View(employeeVM);
        }


        // /Employee/Details/1
        // /Employee/Details
        //[HttpGet]
        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var Employee = await _unitOfWork.EmployeeRepository.Get(id.Value);


            if (Employee is null)
                return NotFound();

            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(Employee);

            return View(viewName, mappedEmp);
        }


        // /Employee/Edit/1
        // /Employee/Edit
        //[HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id, "Edit");
            ///if(id is null)
            ///    return BadRequest();
            ///var Employee = _EmployeeRepository.Get(id.Value);
            ///if (Employee is null)
            ///    return NotFound();
            ///return View(Employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                     _unitOfWork.EmployeeRepository.Update(mappedEmp);
                    await _unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // 1. Log Exception
                    // 2. Friendly Message

                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }
            return View(employeeVM);
        }


        // /Employee/Delete/1
        // /Employee/Delete
        //[HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();
            try
            {
                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                _unitOfWork.EmployeeRepository.Delete(mappedEmp);
                int count = await _unitOfWork.Complete();
                if (count > 0 && employeeVM.ImageName is not null)
                    DocumentSettings.DeleteFile(employeeVM.ImageName, "images");

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                // 2. Friendly Message

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(employeeVM);
            }
        }
    }
}

Demo.PL/Controllers/RoleController.cs
using Demo.DAL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace Demo.PL.Controllers
{
    [Authorize("Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;

        public RoleController(RoleManager<IdentityRole> roleManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _mapper = mapper;
        }

        // /Role/Index
        public async Task<IActionResult> Index(string SearchValue)
        {
            List<IdentityRole> roles = new List<IdentityRole>();

            if (string.IsNullOrEmpty(SearchValue))
                roles.AddRange(_roleManager.Roles.ToList());

            else
            {
                var user = await _roleManager.FindByNameAsync(SearchValue); // RoleName
                roles.Add(user);

            }

            var mappedUsers = _mapper.Map<List<IdentityRole>, List<RoleViewModel>>(roles);
            return View(mappedUsers);


        }


        // /Role/Create
        //[HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel role)
        {
            if (ModelState.IsValid) // Server Side Validation
            {
                var mappedRole = _mapper.Map<RoleViewModel, IdentityRole>(role);

                await _roleManager.CreateAsync(mappedRole);

                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }


        // /Role/Details/1
        // /Role/Details
        //[HttpGet]

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var role = await _roleManager.FindByIdAsync(id);


            if (role is null)
                return NotFound();

            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(role);

            return View(viewName, mappedRole);
        }


        // /Role/Edit/1
        // /Role/Edit
        //[HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel updatedRole)
        {
            if (id != updatedRole.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);

                    role.Name = updatedRole.RoleName;


                    await _roleManager.UpdateAsync(role);

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // 1. Log Exception
                    // 2. Friendly Message

                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }
            return View(updatedRole);
        }


        // /Role/Delete/1
        // /Role/Delete
        //[HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, RoleViewModel deletedRole)
        {
            if (id != deletedRole.Id)
                return BadRequest();
            try
            {
                var user = await _roleManager.FindByIdAsync(id);
                await _roleManager.DeleteAsync(user);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                // 2. Friendly Message

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(deletedRole);
            }
        }
    }
}

Demo.PL/Controllers/UserController.cs
using Demo.DAL.Models;
using Demo.PL.Helpers;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Linq;
using AutoMapper;

namespace Demo.PL.Controllers
{
	public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly IMapper _mapper;

		public UserController(UserManager<ApplicationUser> userManager, IMapper mapper)
        {
			_userManager = userManager;
			_mapper = mapper;
		}

		// /User/Index
		public async Task<IActionResult> Index(string SearchValue)
		{
			List<ApplicationUser> users = new List<ApplicationUser>();

			if (string.IsNullOrEmpty(SearchValue))
				users.AddRange(_userManager.Users.ToList());

			else
			{
				var user = await _userManager.FindByNameAsync(SearchValue); // UserName
				users.Add(user);

			}

			var mappedUsers = _mapper.Map<List<ApplicationUser>, List<UserViewModel>>(users);
			return View(mappedUsers);


		}


		//// /Employee/Create
		////[HttpGet]
		//public IActionResult Create()
		//{
		//	//ViewBag.Departments = _departmentRepository.GetAll();

		//	return View();
		//}

		//[HttpPost]
		//public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
		//{
		//	if (ModelState.IsValid) // Server Side Validation
		//	{
		//		// Manual Mapping
		//		///var mappedEmp = new Employee()
		//		///{
		//		///    Name = employeeVM.Name,
		//		///    Address = employeeVM.Address,
		//		///    Age = employeeVM.Age,
		//		///    DepartmentId = employeeVM.DepartmentId,
		//		///    Email = employeeVM.Email,
		//		///    IsActive = employeeVM.IsActive,
		//		///    PhoneNumber = employeeVM.PhoneNumber,
		//		///    HireDate = employeeVM.HireDate,
		//		///    Salary = employeeVM.Salary
		//		///};

		//		employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

		//		var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

		//		await _unitOfWork.EmployeeRepository.Add(mappedEmp);
		//		// Update
		//		// Delete

		//		await _unitOfWork.Complete();


		//		return RedirectToAction(nameof(Index));
		//	}
		//	return View(employeeVM);
		//}


		// /Employee/Details/1
		// /Employee/Details
		//[HttpGet]

		public async Task<IActionResult> Details(string id, string viewName = "Details")
		{
			if (id is null)
				return BadRequest();
			var user = await _userManager.FindByIdAsync(id);


			if (user is null)
				return NotFound();

			var mappedEmp = _mapper.Map<ApplicationUser, UserViewModel>(user);

			return View(viewName, mappedEmp);
		}


        // /User/Edit/1
        // /User/Edit
        //[HttpGet]
        public async Task<IActionResult> Edit(string id)
		{
			return await Details(id, "Edit");
			
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel updatedUser)
		{
			if (id != updatedUser.Id)
				return BadRequest();

			if (ModelState.IsValid)
			{
				try
				{
					var user = await _userManager.FindByIdAsync(id);

					user.FName = updatedUser.FName;
					user.LName = updatedUser.LName;
					user.PhoneNumber = updatedUser.PhoneNumber;
					//user.Email = updatedUser.Email;
					


					await _userManager.UpdateAsync(user);

					return RedirectToAction(nameof(Index));
				}
				catch (Exception ex)
				{
					// 1. Log Exception
					// 2. Friendly Message

					ModelState.AddModelError(string.Empty, ex.Message);
				}

			}
			return View(updatedUser);
		}


		// /Employee/Delete/1
		// /Employee/Delete
		//[HttpGet]
		public async Task<IActionResult> Delete(string id)
		{
			return await Details(id, "Delete");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete([FromRoute] string id, UserViewModel deletedUser)
		{
			if (id != deletedUser.Id)
				return BadRequest();
			try
			{
				var user = await _userManager.FindByIdAsync(id);
				await _userManager.DeleteAsync(user);

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				// 1. Log Exception
				// 2. Friendly Message

				ModelState.AddModelError(string.Empty, ex.Message);
				return View(deletedUser);
			}
		}
	}
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->


	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	
	@await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

Demo.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string


<td>
    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>

<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>

<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
                <script src="~/lib/jquery/dist/jquery.min.js"></script>

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
    <script>
        const searchBar = $('#searchtext');
        const tableRows = $('table tbody tr');
        searchBar.on('Keyup', function (event) {//h
          
                //enter
              var searchValue =searchBar.val();
              $.ajax({
                  url: '/account/logout',
                  type:'Get',
                  data: {search:searchValue},
                  success:function(result)
                  {
                      console.log(result);
                  },
                  error: function(xhr,status,error)
                  {
                      console.log(error);
                  }
              });
        });
                        const searchBar = $('#searchBar');
                const tableRows = $('table tbody tr');

                searchBar.on('keyup', function (event) {
                    const searchValue = searchBar.val().toLowerCase();

                    tableRows.filter(function () {
                        const text = $(this).text().toLowerCase();
                        const match = text.indexOf(searchValue) > -1;
                        $(this).toggle(match);
                    });
                });
    </script>
</body>

</html>